version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345678aA
      - POSTGRES_DB=coffee-shop
    volumes:
      - coffee_pg_data:/bitnami/postgresql

volumes:
  coffee_pg_data:

